server:
  port: 5001
spring:
  application:
    name: eureka-5001
  profiles: dev
eureka:
  instance:
    hostname: eureka-5001-id #右边名字
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false
---
server:
  port: 5002
spring:
  profiles: prod
  application:
    name: eureka-5002
eureka:
  instance:
    hostname: eureka-5002-id #右边名字
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false
---
server:
  port: 5003
spring:
  profiles: beta
  application:
    name: eureka-5003
eureka:
  instance:
    hostname: eureka-5003-id #右边名字
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false
